### ISSUE TITLE
draw-common.rb:215: NaN (FloatDomainError)

### ISSUE THREAD

**Issue by Spunge** [mruby-zest/mruby-zest#25] opened 2019-07-31 15:30 UTC
I had the zyn-fusion UI crash on me today, giving me the following backtrace:
```
trace:
	[0] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:215:in Draw::WaveForm.env_marker
	[1] /home/johan/packages/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:104:in Nanovg::Context.path
	[2] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:213:in Draw::WaveForm#env_marker
	[3] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:233:in Draw::WaveForm.overlay
	[4] /home/johan/packages/zyn-fusion/src/mruby-zest-build/mruby/mrblib/range.rb:42:in Range.each
	[5] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:227:in Draw::WaveForm#overlay
	[6] src/mruby-zest/qml/Envelope.qml:360:in #<Class:0x5579b2a63590>.draw
	[7] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:164:in DrawSequence.render
	[8] /home/johan/packages/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:116:in Nanovg::Context.spork
	[9] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:162:in DrawSequence.render
	[10] /home/johan/packages/zyn-fusion/src/mruby-zest-build/mruby/mrblib/array.rb:17:in Array.each
	[11] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:160:in DrawSequence.render
	[12] /home/johan/packages/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:90:in Nanovg::Context.draw
	[13] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:159:in DrawSequence.render
	[14] /home/johan/packages/zyn-fusion/src/mruby-zest-build/mruby/mrblib/range.rb:23:in Range.each
	[15] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:139:in DrawSequence.render
	[16] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:528:in ZRunner.draw
	[17] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/time-profile.rb:24:in TimeProfile.time
	[18] /home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:527:in ZRunner.draw
/home/johan/packages/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:215: NaN (FloatDomainError)
[FATAL ERROR] Mruby Is Unable To Continue
```

I was running `zyn-fusion --uri osc.udp://127.0.0.1:14071` from a terminal with zynaddsubfx lv2 running in jalv. I was not interacting with the UI when it crashed.

**Comment by fundamental** [comment] 2019-08-07 11:36
Darn, I had hoped that this bug was resolved after updating the verison
of the mruby interpreter zest builds with. I've heard of this bug
cropping up before, however so far I haven't been able to replicate it
on my system.
I've spent some time relooking over the code and the only place I'm
seeing where a 0.0/0.0->NaN would happen is guarded by what should be a
robust check.
That makes me think that the UI receives a NaN value in a data array and
it gets propigated around.

How long does it tend to take to replicate this issue with the
jalv+external UI combination?
For this to happen I'd assume the envelope visualization must be visible
and notes must be playing.

**Comment by TeTpaAka** [comment] 2020-12-25 17:42
I ran into the same crash running zynaddsubfx as an lv2 plugin in ardour6.
I have an arch linux installation with ardour6 from the repositories and zyn-fusion from AUR.
The gui crashes reliably after a few seconds hammering random keys on my keyboard, both integrated in ardour as well as running `zyn-fusion --uri osc.udp://127.0.0.1:17802`

Attached is an ardour6 project with a single midi channel using the crashing instrument.
[crash.zip](https://github.com/mruby-zest/mruby-zest/files/5742518/crash.zip)

Edit: Fix the attached file

**Comment by fundamental** [comment] 2020-12-27 18:23
@TeTpaAka If possible please include the backtrace of your crash.

**Comment by TeTpaAka** [comment] 2020-12-27 19:17
```
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at /opt/zyn-fusion/
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the developement of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Time for a fast load is 1.441ms load(0.004) class(0.001) spawn(1.436)...
making reverse graph[1091]<1.08 ms>
[INFO:Zyn] zest_setup()
[DEBUG:Zyn] setting up animation fps
trace:
        [0] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:215:in Draw::WaveForm.env_marker
        [1] /home/erik/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:104:in Nanovg::Context.path
        [2] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:213:in Draw::WaveForm#env_marker
        [3] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:233:in Draw::WaveForm.overlay
        [4] /home/erik/zyn-fusion/src/mruby-zest-build/mruby/mrblib/range.rb:42:in Range.each
        [5] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:227:in Draw::WaveForm#overlay
        [6] src/mruby-zest/qml/Envelope.qml:360:in #<Class:0x55caa1ac9e60>.draw
        [7] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:164:in DrawSequence.render
        [8] /home/erik/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:116:in Nanovg::Context.spork
        [9] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:162:in DrawSequence.render
        [10] /home/erik/zyn-fusion/src/mruby-zest-build/mruby/mrblib/array.rb:17:in Array.each
        [11] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:160:in DrawSequence.render
        [12] /home/erik/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:90:in Nanovg::Context.draw
        [13] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:159:in DrawSequence.render
        [14] /home/erik/zyn-fusion/src/mruby-zest-build/mruby/mrblib/range.rb:23:in Range.each
        [15] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/draw-sequence.rb:139:in DrawSequence.render
        [16] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:528:in ZRunner.draw
        [17] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/time-profile.rb:24:in TimeProfile.time
        [18] /home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:527:in ZRunner.draw
/home/erik/zyn-fusion/src/mruby-zest-build/src/mruby-zest/mrblib/draw-common.rb:215: NaN (FloatDomainError)
[FATAL ERROR] Mruby Is Unable To Continue

```

Edit: I saved the crashing instrument without the ardour session: 
[crash.zip](https://github.com/mruby-zest/mruby-zest/files/5745066/crash.zip)

**Comment by fundamental** [comment] 2020-12-28 19:00
Thanks. Looks like it's the same issue. I'll have to see if it's something that can be replicated on my end. It looks like some of the data which describes the envelope points is somehow invalid and that information gets propagated down into one of the drawing routines. It shouldn't happen, but if there's multiple reports of the same thing, something is going wrong somewhere.

**Comment by TeTpaAka** [comment] 2020-12-29 19:06
[crash.zip](https://github.com/mruby-zest/mruby-zest/files/5751828/crash.zip)
I recorded some midi notes that reliably crash zyn-fusion on my system, in case that helps.
I also tried current master of mruby-zest-build and the error is there as well.

Steps to reproduce:
1. open the attached session in ardour
2. open zyn-fusion connecting it with the osc of the ardour plugin
3. switch to the add-synth global amplitude tab
4. play

**Comment by fundamental** [comment] 2021-01-08 22:19
FYI I'm looking into this. A build system issue was a blocker for a few days, but it looks like I have that resolved, so I should be able to get the git HEAD version working on my system again. Getting back to this let's see if I can replicate on my end. As long as that's possible then it's just a matter of tracking the NaN backwards. If I can get it to crash I'll at minimum fix the crash if not the root cause itself. (If I can't then optimistically the changes I had to do with the MRuby interpreter version may have fixed something under the hood and I'll try to get out a demo build to see if it resolves it)

**Comment by fundamental** [comment] 2021-01-09 00:49
Looks like things are running with MRuby 3.0.0. With the standalone I can't replace any issues, but hey it was the same in the past. So now time to rebuild and install the git version on my dev machine and see if I can observe any difference within ardour.

**Comment by fundamental** [comment] 2021-01-09 01:28
Well, that took a bit longer than intended to setup. Looks like there might be a remnant of some problem with setting up the plugin UI with respect to the DPF upgrade that happened in the past few weeks. I might try bugging people a bit closer to those bits and circling back (has to be done pre-release anyhow).

Final error of the day:

> Sending key 'state' to UI failed, out of space

**Comment by TeTpaAka** [comment] 2021-01-09 20:38
I tried running the latest git, now I get a different error.
```
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the development of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Time for a fast load is 1.763ms load(0.005) class(0.0) spawn(1.758)...
making reverse graph[1094]<1.112 ms>
[INFO:Zyn] zest_setup()
[DEBUG:Zyn] setting up animation fps
[WARNING:osc-bridge] Invalid Handle "/part0/kit0/adpars/GlobalPar/AmpEnvelope/Prepeating"...
trace (most recent call last):
src/mruby-zest/qml/Envelope.qml:368:in draw: NaN (FloatDomainError)
[FATAL ERROR] Mruby Is Unable To Continue
```

**Comment by fundamental** [comment] 2021-01-09 21:23
Are you using git for the GUI and git for the backend? If so I'm real puzzled with the preconditions (though that might be solved with the ardour stuff).

**Comment by TeTpaAka** [comment] 2021-01-09 23:55
No, I'm sorry. Since the backend was running fine, I only compiled the GUI.
Now I also compiled the backend and the error doesn't happen anymore.
I'm sorry for your inconvenience.

**Comment by fundamental** [comment] 2021-01-10 00:04
No problem at all. With the error that was appearing it was entirely reasonable to think that it was a bug in the GUI.

Since it sounds like the problem is resolved I'll close the issue, but if you encounter it again, just let me know.

**Closed as completed by fundamental** 2021-01-10 00:04 UTC
Labels: bug
